Repository Ben1152000/sootty, pull requests merged in 2022-09, with the labels that each got.

#56 Fixed bug where logical or breaks query
  sootty/limits.py
  sootty/storage/wire.py
  sootty/storage/wiretrace.py
Labels: bug, query language

#55 Add Extended VCD (EVCD) support
  .gitignore
  README.md
  example/IEEE_std_example.evcd
  example/IEEE_std_example.vcd
  example/example4.evcd
  sootty/__main__.py
  sootty/storage/wiretrace.py
  sootty/utils.py
Labels: enhancement

#63 fix: Windows UnicodeDecodeError: 'gbk' codec
  setup.py
Labels: bug

#59 Add a color list for breakpoints
  sootty/visualizer.py
  tests/test_style.py
Labels: enhancement

#61 Add feature: Print breakpoint table
  README.md
  example/example5.evcd
  sootty/__main__.py
  sootty/storage/valuechange.py
  sootty/storage/wire.py
  sootty/storage/wiregroup.py
  sootty/storage/wiretrace.py
  sootty/utils.py
  sootty/visualizer.py
Labels: enhancement
