Repository Ben1152000/sootty, pull requests merged in 2022-07, with the labels that each got.

#39 Fix LABEL_WIDTH setting
  sootty/visualizer.py
Labels: bug, visualization

#37 Add composite wires to visualizer
  sootty/storage/wiretrace.py
  sootty/visualizer.py
Labels: enhancement, query language

#43 Added modules for save function
  README.md
  install
  sootty/__main__.py
  sootty/limits.py
  sootty/save.py
  sootty/storage/valuechange.py
Labels: documentation, enhancement, query language
